### ISSUE TITLE
error: invalid path 'source/lib/lambda/.prettierignore '

### ISSUE THREAD

**Issue by FlipperC** [aws-solutions/automated-forensic-orchestrator-for-amazon-ec2#10]
As shown in the above error there is a trailing space in the path above causing it to fail on Windows.

Could someone correct this & update?

Thanks!!!

**Comment by ynyany** [comment]
I assume you are building and deploying the solution from a windows machine? this is not currently supported, I'd suggest to build and deploy from a mac/linux machine for now.

**Comment by bios6** [comment]
Hi @FlipperC ,

We suggest you try to build and deploy using a mac/linux machine, this is what we recommend. Closing this issue as it's over an year old and there is a workaround.

Thanks!
