### ISSUE TITLE
Update to Latest Node LTS

### ISSUE THREAD

**Issue by jordan-evans** [aws-solutions/automated-forensic-orchestrator-for-amazon-ec2#23]
**Is your feature request related to a problem? Please describe.**
This solution still required the use of Node 16 which is EOSL. An upgrade to the latest LTS release of node should be a priority

**Describe the feature you'd like**
Use of at least Node 20, if not Node 22 which is the latest LTS release

**Additional context**
N/A

**Comment by abewub** [comment]
As of [release 1.2.2](https://github.com/aws-solutions/automated-forensic-orchestrator-for-amazon-ec2/releases/tag/v1.2.2), the lambda function which required NodeJS 16 runtime is removed.

**Comment by bios6** [comment]
Closing this issue since the lambda was removed in v1.2.2

Thanks!
