### ISSUE TITLE
Npm run build not working on windows

### ISSUE THREAD

**Issue by lakuakuaontop** [aws-solutions/automated-forensic-orchestrator-for-amazon-ec2#3]
The Npm run build command isn't working on windows. 
> forensic-cdk-solution@1.0.0 build
> npm run build:collector && npm run build-lambda

> forensic-cdk-solution@1.0.0 build:collector
> cd lib/lambda; npm ci; npm run build; cd -

The system cannot find the path specified.

**Comment by ynyany** [comment]
this solution is only supports build and deploy from linux/mac environment. We might support Windows should strong singal of requirements supports it.

**Comment by bios6** [comment]
Hi @lakuakuaontop,

We suggest you try to build and deploy using a mac/linux machine, this is what we recommend. Closing this issue as it's over an year old and there is a workaround.

Thanks!
